name: Veracode lf-sample-OAuth-SPA-angular-npm-CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 6'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Npm ci
        run: npm ci

      - name: npm run build-dev
        run: npm run build-dev

      - name: 'create an empty ./veracode folder'
        run: 'mkdir -p ./veracode'

      - name: 'Compress lf-sample-OAuth-SPA-angular-npm'
        run: tar -czvf ./veracode/lf-sample-OAuth-SPA-angular-npm.tar.gz ./dist

      - name: Veracode Upload And Scan (Static Application Security Testing)
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'lf-sample-OAuth-SPA-angular-npm'
          createprofile: true
          filepath: 'veracode'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'

      - name: Run Veracode Software Composition Analysis (SCA)
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.6
        with:
          create-issues: false
          allow-dirty: true
          recursive: true
